function res=effstr2str(str,ressize)
  if(nargin<2)
    ressize=getressize(str)
  end
  if(~isstruct(str))
    if(size(str,1)==1)
      res=repmat(str,ressize,1);
    elseif(size(str,1)==0)
      res=zeros(ressize,0);
    else
      res=str;
    end
  else
    res=struct();
    fnms=fieldnames(str);
    for(i=1:numel(fnms))
      f=getfield(str,fnms{i});
      if(size(f,1)>1)
        ressize=size(f,1);
        break;
      end
    end
    for(i=1:numel(fnms))
      f=effstr2str(getfield(str,fnms{i}),ressize);
      try
      t=mat2cell(f,ones(1,ressize),size(f,2));
      catch,keyboard;end
      if(~exist('fval','var'))
        fval=cell(numel(t),numel(fnms));
      end
      fval(:,i)=t;
    end
    res=cell2struct(fval,fnms,2);
  end
end
function ressize=getressize(str)
    if(~isstruct(str))
      if(size(str,1)~=1)
        ressize=size(str,1);
      else
        ressize=1;
      end
      return;
    end
    fnms=fieldnames(str);
    for(i=1:numel(fnms))
      f=getfield(str,fnms{i});
      ressize=getressize(f);
      if(ressize~=1)
        return;
      end
    end
end
